/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
uint8_t pin_state;
int main(void)
{
	uint32_t *rcc=(uint32_t *)0x40023830;
	uint32_t *mod_d=(uint32_t *)0x40020C00;
	uint32_t *odr_d=(uint32_t *)0x40020C14;
	uint32_t *mod_a=(uint32_t *)0x40020000;
	uint32_t *idr_a=(uint32_t *)0x40020010;
	 uint32_t *pulldown_a = (uint32_t *)0x4002000C;

	*rcc|=(1<<3);//gpiod rcc clock enable
	*rcc|=(1<<0); //gpioa clk enable
	*mod_d&=~(15<<26);//clear bits
	*mod_d|=(5<<26);//config pd13 and pd 14
	*mod_a&=~(3<<1);//pa1 and pa2 as input
	*pulldown_a &= ~(3 << 2); //clear the bit
    *pulldown_a |= (2 << 2);//enable pulldown res for PA1
	*pulldown_a &= ~(3 << 4);//clear the bit
	*pulldown_a |= (2 << 4);//enable pulldown res for PA2
while(1)
	{

			pin_state=(uint8_t)((*idr_a)&(3<<1));// Read PA1 and PA2 (masked)
			switch (pin_state)
			{
			case 6:*odr_d|=(1<<13); // PA1 = 1, PA2 = 1
			*odr_d&=~(1<<14);
			break;
			case 2:*odr_d&=~(3<<13);//PA1 = 1, PA2 = 0
			break;
			case 0:*odr_d|=(1<<14);// PA1 = 0, PA2 = 0
			*odr_d&=~(1<<13);
			break;
			case 4:*odr_d|=(3<<13);// PA1 = 0, PA2 = 1
			break;
			}
}
}
